name: Sync to AWS S3

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (update branch name as needed)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: mamidi9494/cloudpage.in

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to AWS S3
        uses: aws-actions/aws-s3-sync@v2
        with:
          args: --delete --exclude "*.git*"
        env:
          AWS_S3_BUCKET: www.cloudpage.in
          SOURCE_DIR: .
