name: Sync to AWS S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (update branch name as needed)

jobs:
  sync_to_s3_and_invalidate_cache:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -eux {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: mamidi9494/cloudpage.in
          ref: main

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Sync files to AWS S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }}/ --delete --exclude ".git*"
        env:
          AWS_S3_BUCKET: www.cloudpage.in

      - name: Create CloudFront cache invalidation
        run: |
          DISTRIBUTION_ID="${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
